/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cumparaturi;

import Clase.ConnectionDataBase;
import Clase.Produs;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TechSolutions
 */
public class AdaugaCumparatura extends javax.swing.JFrame {
    Produs ProdusNou = new Produs();
    Connection connected = ConnectionDataBase.getDbCon().connect;
    PreparedStatement ps = null;
    ResultSet rs = null;
    DateFormat df = DateFormat.getDateInstance();
    /**
     * Creates new form AdaugaProduse1
     * @throws java.sql.SQLException
     */
    public AdaugaCumparatura() throws SQLException {
        initComponents();
        CumparatorComboBox();
        ProdusComboBox();
        MetodaPlata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbxCumparator = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbxFolosit = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jDataCumparatura = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jcbxcategorie = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jcbxProdusCumparat = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtfPret = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbxMetodaPlata = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cost Management Easy - Adauga Cumparatura");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adauga Cumparatura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jcbxCumparator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alege Cumparator" }));

        jLabel1.setText("Cumparator:");

        jLabel2.setText("Produs Cumparat:");

        jLabel4.setText("Folosit:");

        jcbxFolosit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alege persoana care foloseste produsul !", " " }));

        jLabel5.setText("Data Cumparatura:");

        jDataCumparatura.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        jDataCumparatura.setMaxSelectableDate(new java.util.Date(253370761261000L));
        jDataCumparatura.setMinSelectableDate(new java.util.Date(-62135773139000L));

        jLabel6.setText("Categorie:");

        jcbxcategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alege Categoria Produsului", "Imbracaminte", "Incaltaminte", "Mancare", "MC Donalds", "KFC", "Shaorma", "Sosuri", "Servetele", "Altele", "Cafea", "Tigari", "Tutun Electronic", "Sucuri", "Bere", "Mancare Tomita", "Plase", "Uz caznic", "Sala", "Cursuri" }));

        jButton1.setText("Trimite Inregistrarea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Anuleaza Inregistrarea");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jcbxProdusCumparat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alege produsul" }));
        jcbxProdusCumparat.setToolTipText("");

        jLabel3.setText("Pret:");

        jLabel7.setText("Metoda de plata:");

        jcbxMetodaPlata.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alege metoda de plata" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPret)
                            .addComponent(jcbxFolosit, javax.swing.GroupLayout.Alignment.LEADING, 0, 420, Short.MAX_VALUE)
                            .addComponent(jDataCumparatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbxcategorie, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbxCumparator, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbxProdusCumparat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbxMetodaPlata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxCumparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbxProdusCumparat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbxFolosit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDataCumparatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbxcategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbxMetodaPlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("E-Cost -- Adauga Produse");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ValidareCampuri() throws SQLException{
        if(jcbxCumparator.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Vă rugam selectaţi un cumpărător!");
        }
        else
            if(jcbxProdusCumparat.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null, "Vă rugam să introduce-ţi produsul cumpărat!");
            }
            else
                    if(jcbxFolosit.getSelectedIndex() == 0){
                        JOptionPane.showMessageDialog(null, "Vă rugam selectaţi persoana care foloseste produsul !");
                    }
                    else
                        if(jDataCumparatura.getDate() == null){
                            JOptionPane.showMessageDialog(null, "Vă rugam selectaţi data cand a-ti cumparat produsul !");
                        }
                        else
                            if(jcbxcategorie.getSelectedIndex() == 0){
                                JOptionPane.showMessageDialog(null, "Vă rugam selectaţi categoria produsul !");
                            }
                            else 
                                if(jtfPret.getText().isEmpty()){
                                     JOptionPane.showMessageDialog(null, "Vă rugam introduceti pretul !");
                                }
                                
                                    else{
                                    ExtragereDate();
                                    InserareProdus();
                                    JOptionPane.showMessageDialog(null, "Datele au fost adaugate cu succes !");
                                    setVisible(false);
                                }
    }
    
    private void ExtragereDate(){
        ProdusNou.setCumparator(jcbxCumparator.getSelectedItem().toString());
        ProdusNou.setProdus_cumparat(jcbxProdusCumparat.getSelectedIndex());
        
        BigDecimal pret_produs = new BigDecimal(jtfPret.getText());
        ProdusNou.setPret_produs(pret_produs);
       
        ProdusNou.setPersoana_folosit(jcbxFolosit.getSelectedItem().toString());
        
        Date curent_Date = jDataCumparatura.getDate();
        SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
        String date = format.format(curent_Date);
        ProdusNou.setData_cumparare(date);
        
        ProdusNou.setCategorie(jcbxcategorie.getSelectedItem().toString());
        
        ProdusNou.setMetoda_plata(jcbxMetodaPlata.getSelectedItem().toString());
        
    }
    
    private void InserareProdus() throws SQLException{
    String sql = "Insert into produse_cumparate(cumparator, produs_cumparat, pret_produs, folosit, data_cumparatura , categorie, metoda_plata) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?)";
                ps = connected.prepareStatement(sql);
                ps.setString(1, ProdusNou.getCumparator());
                ps.setInt(2, ProdusNou.getProdus_cumparat());
                ps.setBigDecimal(3, ProdusNou.getPret_produs());
                ps.setString(4, ProdusNou.getPersoana_folosit());
                ps.setString(5, ProdusNou.getData_cumparare());
                ps.setString(6, ProdusNou.getCategorie());
                ps.setString(7, ProdusNou.getMetoda_plata());
                ps.executeUpdate();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            ValidareCampuri();
        } catch (SQLException ex) {
            Logger.getLogger(AdaugaCumparatura.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CumparatorComboBox() throws SQLException{
            String cumparatorOfComboBox = "Select id, prenume from utilizatori";
            ps = connected.prepareStatement(cumparatorOfComboBox);
            rs = ps.executeQuery();
             while(rs.next()){
                int id = rs.getInt("id");
                String prenume =rs.getString("prenume");
                jcbxCumparator.insertItemAt(prenume, id);   
                jcbxFolosit.insertItemAt(prenume, id); 
            }
    }
    
    private void ProdusComboBox() throws SQLException{
        String sql = "Select p.id, p.denumire_produs, m.denumire from produse p left join magazine m on p.magazin = m.id";
        ps = connected.prepareStatement(sql);
            rs = ps.executeQuery();
             while(rs.next()){
                int id = rs.getInt("id");
                String denumire =rs.getString("denumire_produs");
                String denumire_magazin = rs.getString("m.denumire");
                String denumire_concat = denumire + " - " + denumire_magazin;
                jcbxProdusCumparat.insertItemAt(denumire_concat, id);  
            }
    }
    
    private void MetodaPlata() throws SQLException{
        String sql = "Select valoare_parametru from parametri where denumire_parametru = 'metoda_plata'";
        ps = connected.prepareStatement(sql);
            rs = ps.executeQuery();
                while(rs.next()){
                    String denumire = rs.getString("valoare_parametru");
                    jcbxMetodaPlata.addItem(denumire);
                }
    }
    
    
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaugaCumparatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaugaCumparatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaugaCumparatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaugaCumparatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new AdaugaCumparatura().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(AdaugaCumparatura.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private static final javax.swing.JButton jButton2 = new javax.swing.JButton();
    private com.toedter.calendar.JDateChooser jDataCumparatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbxCumparator;
    private javax.swing.JComboBox jcbxFolosit;
    private javax.swing.JComboBox jcbxMetodaPlata;
    private javax.swing.JComboBox jcbxProdusCumparat;
    private javax.swing.JComboBox jcbxcategorie;
    private javax.swing.JTextField jtfPret;
    // End of variables declaration//GEN-END:variables
}
